# Generated by Django 3.2.4 on 2024-12-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1, verbose_name='性别'),
        ),
    ]
